CREATE OR REPLACE PROCEDURE DEL_INV
(INV_ID IN NUMBER) AS
BEGIN
    execute immediate 'ALTER TABLE INVOICELINE
    DROP CONSTRAINT FK_InvoiceLineInvoiceId';
    execute immediate 'ALTER TABLE INVOICELINE
    ADD CONSTRAINT FK_InvoiceLineInvoiceId
    FOREIGN KEY (INVOICEID)
    REFERENCES INVOICE(INVOICEID) ON DELETE CASCADE';
    DELETE FROM INVOICE WHERE INVOICEID = INV_ID;
    COMMIT;
END;
/