conn chinook/p4ssw0rd

INSERT INTO GENRE(NAME) VALUES ('DUBSTEP');
INSERT INTO GENRE(NAME) VALUES ('ASMR');
INSERT INTO EMPLOYEE(EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES (9, "Ross', 'Bob');
INSERT INTO EMPLOYEE(EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES (10, 'Swanson', 'Ron');
INSERT INTO CUSTOMER(CUSTOMERID, LASTNAME, FIRSTNAME) VALUES (60, 'Ross', 'Bob');
INSERT INTO CUSTOMER(CUSTOMERID, LASTNAME, FIRSTNAME) VALUES (61, 'Swanson', 'Ron');


exit;

