
CREATE OR REPLACE FUNCTION INVOICEAVG RETURN NUMBER AS Z NUMBER;

BEGIN
    SELECT AVG(Total) INTO Z FROM INVOICE;
    RETURN Z;
END;
/

CREATE OR REPLACE FUNCTION MOSTEXPTRACK RETURN NUMBER AS Z NUMBER;

BEGIN
    
    SELECT MAX(TRACKID) INTO Z FROM TRACK WHERE UNITPRICE = (SELECT MAX(UNITPRICE) FROM TRACK);
    RETURN Z;
END;
/


DECLARE
    INVA NUMBER;
BEGIN
    INVA:=INVOICEAVG;
    DBMS_OUTPUT.PUT_LINE('Average of all Invoice Totals: '|| INVA);
END;
/

DECLARE
    MOSTEXP NUMBER;
BEGIN
    MOSTEXP:=MOSTEXPTRACK;
    DBMS_OUTPUT.PUT_LINE('Most Expensive Track ID: '|| MOSTEXP);
END;
/