conn chinook/p4ssw0rd

CREATE OR REPLACE FUNCTION GET_TIME RETURN TIMESTAMP AS Z TIMESTAMP;
BEGIN
    Z:= SYSTIMESTAMP;
    RETURN Z;
END;
/

CREATE OR REPLACE FUNCTION MEDIA_LENGTH (MEDIA_ID IN NUMBER) RETURN NUMBER AS Z NUMBER;

Cursor C1 IS SELECT LENGTH(Name) FROM MEDIATYPE WHERE MediaTypeId = MEDIA_ID;
BEGIN
    OPEN C1;
    FETCH C1 into Z;
    RETURN Z;
END;
/

DECLARE
    MEDIALEN NUMBER;
BEGIN
    MEDIALEN:= MEDIA_LENGTH(1);
    DBMS_OUTPUT.PUT_LINE('Length of first Mediatype: ' || MEDIALEN);
END;
/

--exit;
