conn chinook/p4ssw0rd
/*
SELECT * FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert');

SELECT * FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert'));

SELECT * FROM INVOICELINE
WHERE INVOICEID IN (SELECT INVOICEID FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert')));
*/

DELETE FROM INVOICELINE
WHERE INVOICEID IN (SELECT INVOICEID FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert')));

DELETE FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert'));

DELETE FROM CUSTOMER WHERE
(LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert');

exit;

