CREATE OR REPLACE PROCEDURE SP_UPDATE_EMPLOYEE
(E_ID IN NUMBER, E_FNAME IN VARCHAR, E_LNAME IN VARCHAR) AS
BEGIN

    UPDATE EMPLOYEE
    SET FirstName = E_FNAME, LastName = E_LNAME
    WHERE EmployeeID = E_ID;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE GET_EMP_MANAGER
(E_ID IN NUMBER, Z OUT NUMBER) AS
BEGIN
    SELECT REPORTSTO INTO Z FROM EMPLOYEE WHERE EMPLOYEEID = E_ID;
END;
/

DECLARE
    X NUMBER;
BEGIN
    GET_EMP_MANAGER(3,X);
    DBMS_OUTPUT.PUT_LINE('Manager ID: '|| X);
END;
/