
CREATE OR REPLACE FUNCTION INVOICELINEAVG RETURN NUMBER AS Z NUMBER;

BEGIN
    SELECT AVG(UnitPrice) INTO Z FROM INVOICELINE;
    RETURN Z;
END;
/


DECLARE
    INVLINAVG NUMBER;
BEGIN
    INVLINAVG:= INVOICELINEAVG;
    DBMS_OUTPUT.PUT_LINE('Average of specified InvoiceLine UnitPrice: '|| INVLINAVG);
END;
/
