conn chinook/p4ssw0rd
/*
SELECT * FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert');

SELECT * FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert'));

SELECT * FROM INVOICELINE
WHERE INVOICEID IN (SELECT INVOICEID FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert')));
*/

/*
DELETE FROM INVOICELINE
WHERE INVOICEID IN (SELECT INVOICEID FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert')));

DELETE FROM INVOICE
WHERE CUSTOMERID = (SELECT CUSTOMERID FROM CUSTOMER
WHERE (LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert'));

DELETE FROM CUSTOMER WHERE
(LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert');
*/
ALTER TABLE INVOICELINE
    DROP CONSTRAINT FK_InvoiceLineInvoiceId;

ALTER TABLE INVOICELINE
    ADD CONSTRAINT FK_InvoiceLineInvoiceId
    FOREIGN KEY (INVOICEID)
    REFERENCES INVOICE(INVOICEID) ON DELETE CASCADE;

ALTER TABLE INVOICE
    DROP CONSTRAINT FK_InvoiceCustomerId;
    
ALTER TABLE INVOICE
    ADD CONSTRAINT FK_InvoiceCustomerId
    FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE;

DELETE FROM CUSTOMER WHERE
(LASTNAME = 'Walter') AND (FIRSTNAME = 'Robert');

exit;

