conn chinook/p4ssw0rd

INSERT INTO GENRE(NAME, GenreId) VALUES ('DUBSTEP', 26);
INSERT INTO GENRE(NAME, GenreId) VALUES ('ASMR', 27);
INSERT INTO EMPLOYEE(EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES (9, 'Ross', 'Bob');
INSERT INTO EMPLOYEE(EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES (10, 'Swanson', 'Ron');
INSERT INTO CUSTOMER(CUSTOMERID, LASTNAME, FIRSTNAME, EMAIL) VALUES (60, 'Ross', 'Bob','BobRoss@fakemail.com');
INSERT INTO CUSTOMER(CUSTOMERID, LASTNAME, FIRSTNAME, EMAIL) VALUES (61, 'Swanson', 'Ron','RonSwanson@fakemail.com');

exit;

