CREATE OR REPLACE FUNCTION GET_TIME RETURN TIMESTAMP AS Z TIMESTAMP;
BEGIN
    Z:= LOCALTIMESTAMP;
    RETURN Z;
END;
/

CREATE OR REPLACE FUNCTION MEDIA_LENGTH (MEDIA_ID IN NUMBER) RETURN NUMBER AS Z NUMBER;

BEGIN
    SELECT LENGTH(Name) INTO Z FROM MEDIATYPE WHERE MediaTypeId = MEDIA_ID;
    RETURN Z;
END;
/

SELECT GET_TIME FROM DUAL;
SELECT MEDIA_LENGTH(1) FROM MEDIATYPE;

DECLARE
    TM TIMESTAMP;
    MEDIALEN NUMBER;
BEGIN
    TM:= GET_TIME;
    DBMS_OUTPUT.PUT_LINE(TM);
    MEDIALEN:= MEDIA_LENGTH(1);
    DBMS_OUTPUT.PUT_LINE('Length of first Mediatype: '|| MEDIALEN);
END;
/